version: '3'
services:
  webserver:
    build: docker
    image: node-express-dev:1.0
    container_name: node
    tty: true
    volumes:
        - ../TestEnvironment:/app
        - /app/node_modules
    ports:
        - "8080:3000"
