version: '3'
services:
  webserver:
    build: docker
    image: node-express-dev:1.0
    container_name: node
    tty: true
    volumes:
        # - ./node/app:/app
        - ../TestEnvironment:/app
    ports:
        - "8080:3000"
